# Generated by Django 3.2.5 on 2024-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_user_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/images/profiles/default.png', upload_to='staticfiles/images/profiles/'),
        ),
    ]
