# Generated by Django 3.2.5 on 2024-10-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameResult',
        ),
    ]
